//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_AssignmentX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapLocation
    {
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public string longitude { get; set; }
        public string Latitude { get; set; }
        public string Description { get; set; }
    }
}
