//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_MyAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Moves
    {
        [Required]
        public int MoveID { get; set; }
        [Required]
        public string MoveName { get; set; }
        [Required]
        public short Times { get; set; }
        [Required]
        public short Rounds { get; set; }

        [Required]
        public System.DateTime Date { get; set; }
    }
}
